+incdir+/Users/mikail/Projects/stud/vlsi2_croc/.bender/git/checkouts/socc_on_croc-86a23edf71b97bbc/rtl/generated/include
+incdir+/Users/mikail/Projects/stud/vlsi2_croc/rtl/apb/include
+incdir+/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/include
+incdir+/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/include
+incdir+/Users/mikail/Projects/stud/vlsi2_croc/rtl/idma/include
+incdir+/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi/include
+define+TARGET_FLIST
+define+TARGET_RTL
+define+TARGET_SYNTHESIS
+define+TARGET_VERILATOR
+define+VERILATOR=1
+define+COMMON_CELLS_ASSERTS_OFF=1
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_verification/clk_rst_gen.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/tech_cells_generic/tc_sram.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/tech_cells_generic/tc_sram_impl.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/tech_cells_generic/tc_clk.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/binary_to_gray.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/cb_filter_pkg.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/cc_onehot.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/cdc_reset_ctrlr_pkg.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/cf_math_pkg.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/clk_int_div.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/credit_counter.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/delta_counter.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/ecc_pkg.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/edge_propagator_tx.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/exp_backoff.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/fifo_v3.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/gray_to_binary.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/heaviside.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/isochronous_4phase_handshake.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/isochronous_spill_register.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/lfsr.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/lfsr_16bit.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/lfsr_8bit.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/lossy_valid_to_stream.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/mv_filter.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/onehot_to_bin.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/plru_tree.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/passthrough_stream_fifo.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/popcount.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/ring_buffer.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/rr_arb_tree.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/rstgen_bypass.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/serial_deglitch.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/shift_reg.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/shift_reg_gated.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/spill_register_flushable.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/stream_demux.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/stream_filter.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/stream_fork.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/stream_intf.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/stream_join_dynamic.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/stream_mux.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/stream_throttle.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/sub_per_hash.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/sync.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/sync_wedge.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/unread.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/read.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/addr_decode_dync.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/boxcar.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/cdc_2phase.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/cdc_4phase.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/clk_int_div_static.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/trip_counter.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/addr_decode.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/addr_decode_napot.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/multiaddr_decode.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/cb_filter.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/cdc_fifo_2phase.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/clk_mux_glitch_free.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/counter.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/ecc_decode.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/ecc_encode.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/edge_detect.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/lzc.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/max_counter.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/rstgen.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/spill_register.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/stream_delay.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/stream_fifo.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/stream_fork_dynamic.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/stream_join.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/cdc_reset_ctrlr.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/cdc_fifo_gray.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/fall_through_register.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/id_queue.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/stream_to_mem.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/stream_arbiter_flushable.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/stream_fifo_optimal_wrap.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/stream_register.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/stream_xbar.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/cdc_fifo_gray_clearable.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/cdc_2phase_clearable.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/mem_to_banks_detailed.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/stream_arbiter.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/stream_omega_net.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/common_cells/mem_to_banks.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi/obi_pkg.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi/obi_intf.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi/obi_rready_converter.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi/apb_to_obi.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi/obi_to_apb.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi/obi_atop_resolver.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi/obi_cut.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi/obi_demux.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi/obi_err_sbr.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi/obi_mux.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi/obi_sram_shim.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi/obi_xbar.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/apb/apb_pkg.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/cve2_pkg.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/cve2_alu.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/cve2_branch_predict.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/cve2_compressed_decoder.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/cve2_controller.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/cve2_counter.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/cve2_csr.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/cve2_decoder.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/cve2_fetch_fifo.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/cve2_load_store_unit.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/cve2_multdiv_fast.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/cve2_multdiv_slow.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/cve2_pmp.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/cve2_register_file_ff.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/cve2_wb.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/cve2_cs_registers.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/cve2_ex_block.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/cve2_id_stage.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/cve2_prefetch_buffer.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/cve2_if_stage.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/cve2/cve2_core.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/idma/idma_pkg.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/idma/idma_channel_coupler.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/idma/idma_dataflow_element.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/idma/idma_obi_read.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/idma/idma_obi_write.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/idma/idma_nd_midend.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/idma/idma_transfer_id_gen.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/idma/idma_legalizer_page_splitter.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/idma/idma_transport_layer_rw_obi.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/idma/idma_legalizer_rw_obi.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/idma/idma_backend_rw_obi.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/idma/croc_idma.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi_uart/obi_uart_pkg.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi_uart/obi_uart_baudgen.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi_uart/obi_uart_interrupts.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi_uart/obi_uart_modem.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi_uart/obi_uart_rx.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi_uart/obi_uart_tx.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi_uart/obi_uart_register.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi_uart/obi_uart.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/riscv-dbg/dm_pkg.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/riscv-dbg/debug_rom/debug_rom.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/riscv-dbg/debug_rom/debug_rom_one_scratch.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/riscv-dbg/dm_csrs.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/riscv-dbg/dm_mem.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/riscv-dbg/dmi_cdc.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/riscv-dbg/dmi_jtag_tap.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/riscv-dbg/dm_sba.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/riscv-dbg/dm_top.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/riscv-dbg/dmi_jtag.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/riscv-dbg/dm_obi_top.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/riscv-dbg/tb/jtag_test_simple.sv
/Users/mikail/Projects/stud/vlsi2_croc/.bender/git/checkouts/socc_on_croc-86a23edf71b97bbc/rtl/address_generator.sv
/Users/mikail/Projects/stud/vlsi2_croc/.bender/git/checkouts/socc_on_croc-86a23edf71b97bbc/rtl/color_generator.sv
/Users/mikail/Projects/stud/vlsi2_croc/.bender/git/checkouts/socc_on_croc-86a23edf71b97bbc/rtl/glyph_ram_wrapper.sv
/Users/mikail/Projects/stud/vlsi2_croc/.bender/git/checkouts/socc_on_croc-86a23edf71b97bbc/rtl/glyph_rom_wrapper.sv
/Users/mikail/Projects/stud/vlsi2_croc/.bender/git/checkouts/socc_on_croc-86a23edf71b97bbc/rtl/obi_sub.sv
/Users/mikail/Projects/stud/vlsi2_croc/.bender/git/checkouts/socc_on_croc-86a23edf71b97bbc/rtl/socc_on_croc.sv
/Users/mikail/Projects/stud/vlsi2_croc/.bender/git/checkouts/socc_on_croc-86a23edf71b97bbc/rtl/sync_generator.sv
/Users/mikail/Projects/stud/vlsi2_croc/.bender/git/checkouts/socc_on_croc-86a23edf71b97bbc/rtl/text_ram_wrapper.sv
/Users/mikail/Projects/stud/vlsi2_croc/.bender/git/checkouts/socc_on_croc-86a23edf71b97bbc/rtl/generated/font_rom.sv
/Users/mikail/Projects/stud/vlsi2_croc/.bender/git/checkouts/socc_on_croc-86a23edf71b97bbc/rtl/generated/glyph_rom.sv
/Users/mikail/Projects/stud/vlsi2_croc/.bender/git/checkouts/socc_on_croc-86a23edf71b97bbc/rtl/testing/obi_manager.sv
/Users/mikail/Projects/stud/vlsi2_croc/.bender/git/checkouts/socc_on_croc-86a23edf71b97bbc/rtl/testing/obi_tester.sv
/Users/mikail/Projects/stud/vlsi2_croc/.bender/git/checkouts/socc_on_croc-86a23edf71b97bbc/target/sim/rtl/socc_on_croc_utils_pkg.sv
/Users/mikail/Projects/stud/vlsi2_croc/.bender/git/checkouts/socc_on_croc-86a23edf71b97bbc/target/sim/rtl/tb_socc_on_croc.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/croc_pkg.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/user_pkg.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/soc_ctrl/soc_ctrl_regs_pkg.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/gpio/gpio_reg_pkg.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/clint/clint_reg_pkg.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi_timer/obi_timer_reg_pkg.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/core_wrap.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/bootrom/bootrom.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/soc_ctrl/soc_ctrl_regs.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/gpio/gpio_reg_top.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/gpio/gpio.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/clint/clint.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/obi_timer/obi_timer.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/croc_domain.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/user_domain.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/croc_soc.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/croc_chip.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/test/tb_croc_pkg.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/test/croc_vip.sv
/Users/mikail/Projects/stud/vlsi2_croc/rtl/test/tb_croc_soc.sv

